services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - 8787:8787
    volumes:
      - ./apps/backend:/app/apps/backend
      - /app/apps/backend/node_modules
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - /app/apps/frontend/node_modules
    
