CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE, 
  password TEXT NOT NULL, 
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP 
);

-- status => 0: 未完了, 1: 完了
CREATE TABLE IF NOT EXISTS todos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  content TEXT, 
  "status" INTEGER NOT NULL, 
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP 
);

CREATE INDEX titleindex ON todos(title);
CREATE INDEX statusindex ON todos("status");
